- src/CachedBuilder.php
Added `orderBy()` clauses to cachable, to cache sorted queries.
> Add Builder orders to Cachable Key

- tests/Unit/CachedBuilderTest.php
This was a bit of fiddling but this exercises the currently uncovered branch as seen here: https://coveralls.io/builds/13692274/source?filename=src%2FCachedBuilder.php#L93
Fixes issue #17
> Add unit test for raw clause parsing

- CHANGELOG.md
- README.md
- phpunit.xml
- src/CachedBuilder.php
- src/CachedModel.php
- tests/Unit/CachedBuilderTest.php
- tests/Unit/CachedModelTest.php
- tests/Unit/DisabledCachedBuilderTest.php
- tests/Unit/DisabledCachedModelTest.php
> Implement optional disabling of caching

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- config/laravel-model-caching.php
- phpunit.xml
- src/CachedBuilder.php
- src/CachedModel.php
- src/Providers/Service.php
- src/Traits/Cachable.php
- tests/CreatesApplication.php
- tests/Unit/Traits/CachableTest.php
> Laravel 5.5

- README.md
- src/CachedModel.php
- src/Traits/Cachable.php
mostly just moving the code into the cachable trait, altohugh also cleaned up the boot method a little
the model instance gets passed to the event listeners by laravel anyway, and saved gets called for all the events so no need to handle created/updated/deleted as well
> Move the logic into a trait, so it is accessible without extending the provided base model (eg for projects which already have a base model)

- src/Traits/Cachable.php
in reference to issue:
https://github.com/GeneaLabs/laravel-model-caching/issues/75
The explanation there is extensive.
> Removing session driver dependancy, using cache

- src/Traits/Cachable.php
In order for my mongodb models to be able to extend this trait, I had to make a CachedModel of my own as seen below
```
use GeneaLabs\LaravelModelCaching\CachedBuilder as Builder;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
abstract class _CachedMongoModel extends Eloquent
{
use Cachable;
... rest is the same as your CachedModel
}
```
But then the above check was a blocker. Upon inspection it seems like there's no reason to make this check since we can assume anyone using your trait is using it with your CachedModel (or an adapted clone as in my case)
> remove unneeded check to make compatible with mongodb

- config/laravel-model-caching.php
currently not retrieving the correct variable from .env file
> typo fix in config/laravel-model-caching.php

- composer.json
- src/CacheKey.php
- tests/Integration/CachedBuilder/WhereRawTest.php
- tests/Integration/CachedBuilderRelationshipsTest.php
Removed unnecessary binding advancement. 
Solves issue with yajra/laravel-datatables global search (#139)
> Fix nested where binding issue

- src/Console/Commands/Clear.php
- src/Traits/Caching.php
- tests/CreatesApplication.php
- tests/Integration/Traits/CachableTest.php
This PR fixes several issues, that i found working with Lumen.
1. Lumen don't have `cache()` helper.
2. [This issue](https://github.com/GeneaLabs/laravel-model-caching/issues/148).
> Lumen support

- src/CachedBuilder.php
This PR fixed a Lumen bug mentioned in Issue #198 . 
Changed `request()` helper function into `app('request')`
> Fixed missing function bug in Lumen.

- src/Traits/Caching.php
I execute `${cachableModel}->scopeWithCacheCooldownSeconds`.
But `cooldown seconds` never been changed.
So, I found this problem in `Caching::checkCooldownAndRemoveIfExpired`.
(Maybe copy and paste code but not changed from `cooldown:invalidated-at` to `cooldown:seconds` ?)
> Fix never forget cooldown seconds in checkCooldownAndRemoveIfExpired.

- src/CacheKey.php
- tests/Integration/CachedBuilder/WhereInTest.php
Currently, when running a `whereIn`, where the collection checking against is empty an exception will be thrown. This fixes the issue, evidenced by the test.
> Handle whereIn when collection is empty

- src/CachedBuilder.php
- src/Traits/ModelCaching.php
This is an attempt to fix the reason why `scopeDisableCache()` global scope is not working.
@mikebronner if this is supposed to be actually set to `true` for some reason, let me know. I believe it is meant to be false though.
See #106 and #231
> When model cache disabled, it is correctly disabled on query and all eager loaded relations

- src/Traits/CachePrefixing.php
While running integration and feature tests using SQLite driver and the query is not completed initialized in a multitenant scenario and for example the output of `$this->query->toSql()` will be `select *` or `1`, this will fallback to the default connection instead of using the proper model connection.
Fix #272
> Fix model connection for SQLite tests

- tests/Feature/PaginationTest.php
- tests/Integration/CachedBuilder/PaginateTest.php
- tests/Integration/CachedBuilderTest.php
While working on the non cacheable test I submitted earlier I noticed that a couple of the tests used `'` instead of `"` which would stop the variable parsing.
> Fixed string template syntax in CachedBuilderTest

- tests/Integration/CachedBuilderRelationshipsTest.php
This is a test to demostrate the bug discussed in #292. I have tried to use existing test classes and models but I can adapt it to create bespoke ones. Let me know if this is OK.
> Testing for clearing of eager loaded non cacheable relations

- tests/Integration/CachedBuilder/WhereHasMorphTest.php
- tests/database/seeds/DatabaseSeeder.php
Added in laravel 6 thought it might have required some changes but appears to work great :)
> Add whereHasMorph test

- src/CacheKey.php
- Skip adding currentBinding in the CacheKey class if the where values are not in the query binding.
> Skip adding currentBinding if the where values are not in the query binding

- .travis.yml
It appears when you merged in the master build passed but it failed to install nova and therefore didn't run those tests hopefully this fixes it although you might just want to do some trial and error on master instead of merging this PR.
> Fix nova install

- src/CacheKey.php
- tests/Integration/CachedBuilder/ScopeTest.php
Fixes #342 
I have made these changes and it seems to fix the issues I raised in issue #342 
The PR adds more detail to the key, uncluding the scope bindings - this means when we reach into the cache, we take into account the global scope bindings (if any) and use this to generate a more accurate key
> ~ fixes all method not recognising change to global scope params

- .github/workflows/laravel.yml
Its common to do a matrix for supported PHP versions and to cache composer dependencies for faster runs. And made it so they do not fail due to nova on PRs
> Add PHP matrix and skip nova on PR

- src/Traits/Buildable.php
- tests/Integration/CachedBuilder/ScopeTest.php
This should fix #289 by overriding the builders implementation of `applyScopes()` to make it check if scopes have been applied already before attempting to apply them again.
> Add some code to stop scopes from being applied twice.

- src/Traits/ModelCaching.php
Fixes #381 
So this changes the method signature to use the `Eloquent/Builder` class directly in the method signature rather than the alias. 
I created an example repo to replicate this issue here:
https://github.com/dmason30/model-caching-example
This is the test used:
https://github.com/dmason30/model-caching-example/blob/master/tests/Unit/ExampleTest.php
**Before fix**
Replicated action: https://github.com/dmason30/model-caching-example/runs/1359149642?check_suite_focus=true
<details>
<summary>Shows PHP 7.3 Warning</summary>
</details>
<details>
<summary>Shows PHP 7.4 Warning</summary>
</details>
**After fix**
Example repo changed to use fork: https://github.com/dmason30/model-caching-example/pull/1/files
Fix action: https://github.com/dmason30/model-caching-example/runs/1359345868?chec …
> Fix newBelongsToMany method compatibility

- CHANGELOG.md
- src/CacheKey.php
Why ?
I have the following model:
```php
class DemoUnscoped {
public $table = 'demo_unscoped';
public function scopeFooBar($query)
{
$query->from('demo_scoped');
return $query;
}
}
```
Now, assuming my table demo_unscoped has 666 entries, and demo_scoped has 999 entries, prior to this patch i get the following results:
```
DemoUnscoped::count();
666
DemoUnscoped::FooBar()->count();
666 // <----------- WRONG (has cached the value but should not!)
```
With this fix applied i get:
```
DemoUnscoped::count();
666
DemoUnscoped::FooBar()->count();
999 // <----------- Correct ! 
```
> Use the part of the query (->from) instead of the table name of the model (->table)

- composer.json
Hi,
I believe this package was accidentally included in require instead of require-dev which means that when using this package and running `composer install --no-dev` this heavy package is still installed.
I use vapor which has size limits and this change threw us over the limit.
> Move slevomat/coding-standard to require-dev

- src/Traits/Buildable.php
This fixes pagination when using Livewire, which is currently broken due to how it sets the current page.
Relates to: https://github.com/GeneaLabs/laravel-model-caching/issues/377
> Use Paginator to resolve current page.

- src/Traits/Buildable.php
No caching currently present for `exists` statements so have extended this method to add this functionality :)
> Adding exists to Buildable

- src/CacheKey.php
- tests/Integration/CachedBuilder/BooleanTest.php
- tests/Integration/CachedBuilder/PolymorphicOneToManyTest.php
- tests/Integration/CachedBuilder/PolymorphicOneToOneTest.php
This bug is difficult to explain clearly so I will try my best.
I discovered it when I was trying query where a relation had a false column then using a `whereRaw` after. See this example below from the added test in this PR:
```php
$books = (new Book)
->whereHas('author', function ($query) {
return $query->where('is_famous', false); // Passing false here is the issue
})
->whereRaw("title = ?", ['Mixed Clause']) // This binding ends up not being included in the cache key
->get();
```
**Issue**
Before this PR fix the cache key that is generated would be missing the 'Mixed Clause' binding see below where the key ends without the value. 
```
-exists-and_books.author_id_=_authors.id-is_famous_=_-authors.deleted_at_null-_and_title_=
```
**Workaround**
If you use zero instead as the value …
> [bug] Fix current binding count when previous binding is false

- src/CacheKey.php
- src/Traits/BuilderCaching.php
- src/Traits/Caching.php
- tests/Integration/CachedBuilder/ScopeTest.php
The intention of this PR is to add in support for the `withoutGlobalScope` and `withoutGlobalScopes` function in Eloquent (https://laravel.com/docs/8.x/eloquent#removing-global-scopes).
When an application using the Caching Library applies the `withoutGlobalScopes()` modifier to a model, the global scopes are currently being added back in by the Caching Library.  This requires the client application to disable the cache, `disableCache()`, prior to calling `withoutGlobalScopes`. This PR should fix that.
> Add support for withoutGlobalScopes

- src/Traits/ModelCaching.php
- tests/Integration/CachedBuilder/BelongsToManyTest.php
As title describes, we've multiple issues on our Laravel 9 based project when users saving stuff on our API.
Apparently this "stuff" has all to do with using sync (in multiple cases required for our business logic to work with the feature design).
So that's how I've found that the **`pivotSynced` event was already available in laravel-pivot-events but not mentioned here**.
I'll later today send some commits verifying / testing this scenario I had
> Add pivotSynced event listener to flush cache when performing BelongsToMany::sync

- .github/workflows/laravel.yml
- .gitignore
- composer.json
- src/CacheKey.php
- tests/CreatesApplication.php
- tests/Feature/PaginationTest.php
- tests/Fixtures/Book.php
- tests/Fixtures/BookWithUncachedStore.php
- tests/Fixtures/UncachedBook.php
- tests/Fixtures/UncachedBookWithStores.php
- tests/Integration/CachedBuilder/PaginateTest.php
This PR includes the necessary changes for Laravel 10. (https://github.com/GeneaLabs/laravel-model-caching/issues/439)
I am unable to verify if the Nova tests are passing since I do not have a Laravel Nova account. However, all other tests are passing.
> Add support for Laravel 10

- src/Traits/Buildable.php
Fixes the issue referenced in #445. Laravel 10.3.0 added a `$total` parameter to `Illuminate\Database\Eloquent\Builder::paginate`. This PR adds the same parameter to `GeneaLabs\LaravelModelCaching\Traits\Buildable::paginate` to eliminate PHP errors about a mismatch in function signature.
> Make Buildable@paginate compatible with Laravel 10.3.0

- src/CacheKey.php
Fix warnings with JsonContainsKey where clause
<warning> WARNING </warning> Undefined array key "operator" in vendor/genealabs/laravel-model-caching/src/CacheKey.php on line 272. <warning> DEPRECATED </warning> strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/genealabs/laravel-model-caching/src/CacheKey.php on line 272.
Add JsonContainsKey type
> JsonContainsKey supported

- src/CacheKey.php
Fix exception: Object of class Illuminate\Database\Query\Expression could not be converted to string
Related: https://github.com/GeneaLabs/laravel-model-caching/issues/441
Eloquent query that caused the bug, for example:
```
$this
->vigilances()
->has('investigations', '=', 1);
```
If i try to dump $where variable and got:
```
array:5 [▼ // vendor/genealabs/laravel-model-caching/src/CacheKey.php
"type" => "Basic"
"column" => Illuminate\Database\Query\Expression {#4958 ▼
#value: "(select count(*) from `investigations` inner join `investigation_vigilance` on `investigations`.`id` = `investigation_vigilance`.`investigation_id` where `vigilances`.`id` = `investigation_vigilance`.`vigilance_id` and `investigations`.`deleted_at` is null) ◀"
}
"operator" => "="
"value" => …
```
> Add expressionToString to getOtherClauses

- src/Traits/Caching.php
When MODEL_CACHE_ENABLED is set to false, checkCooldownAndFlushAfterPersisting is still running logic which opens a cache connection.
`[2024-02-25 04:34:58] local.ERROR: No connection could be made because the target machine actively refused it {"exception":"[object] (RedisException(code: 0): No connection could be made because the target machine actively refused it at \\vendor\\laravel\\framework\\src\\Illuminate\\Redis\\Connectors\\PhpRedisConnector.php:159)
[stacktrace]
#0 \\vendor\\laravel\\framework\\src\\Illuminate\\Redis\\Connectors\\PhpRedisConnector.php(159): Redis->connect('127.0.0.1', '6379', 0.0, NULL, 0, 0.0)
#1 \\vendor\\laravel\\framework\\src\\Illuminate\\Redis\\Connectors\\PhpRedisConnector.php(88): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Obje …
> Ensure isCachable in checkCooldownAndFlushAfterPersisting

- src/CacheKey.php
This should fix #470 by making sure all columns are strings before imploding them.
> Fix cachekey issue

- src/Traits/Caching.php
Takes into account Carbon v3 new default parameter value on the `diffInSeconds` method.
Carbon v2 method blueprint:
```
public function diffInSeconds($date = null, $absolute = true)
```
Carbon v3 method blueprint:
```
public function diffInSeconds($date = null, bool $absolute = false): float
```
Fixes failing tests:
https://github.com/mikebronner/laravel-model-caching/blob/a38c905790c73c43dac09790eec7f0972cd651cc/tests/Integration/CachedModelTest.php#L180
> [Fix] Carbon v3 new method default parameter compatibility

- src/Traits/BuilderCaching.php
- src/Traits/ModelCaching.php
> fix deprecations with nullable func args in php 8.4
